#create it_company database

-- DELETE OLD DATABASE (so no errors)
DROP DATABASE IF EXISTS IT_COMPANY;

-- CREATE NEW DATABASE
CREATE DATABASE IT_COMPANY1;

USE IT_COMPANY1;

-- CREATE DEPT TABLE
CREATE TABLE DEPT(
    DEPTID INT NOT NULL PRIMARY KEY,
    DEPTNAME VARCHAR(30) NOT NULL UNIQUE
);

-- CREATE EMPLOYEE TABLE
CREATE TABLE EMPLOYEE(
     EMPID INT AUTO_INCREMENT,
     NAME VARCHAR(40) NOT NULL,
     DEPTID INT NOT NULL,
     SALARY INT UNSIGNED,
     PRIMARY KEY(EMPID),
     FOREIGN KEY (DEPTID) REFERENCES DEPT(DEPTID)
);

-- INSERT RECORDS IN DEPT TABLE
INSERT INTO DEPT VALUES
(1001,'IT'),
(1002,'HR'),
(1003,'SALES');

SELECT * FROM DEPT;

-- INSERT INTO EMPLOYEE
INSERT INTO EMPLOYEE(NAME,DEPTID,SALARY)
VALUES
('RAM',1001,50000),
('RAJU',1002,45000);

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE(NAME,DEPTID,SALARY)
VALUES('SAM',1001,50000);

INSERT INTO EMPLOYEE(NAME,DEPTID,SALARY)
VALUES('SANJU',1002,50000);

INSERT INTO EMPLOYEE(NAME,DEPTID,SALARY)
VALUES
('SIVA',1001,55000),
('GEETHU',1003,40000);

SELECT * FROM EMPLOYEE;

DESC DEPT;

-- SELECT IT EMPLOYEES
SELECT * FROM EMPLOYEE
WHERE DEPTID = 1001;

-- SELECT NON IT EMPLOYEES
SELECT * FROM EMPLOYEE
WHERE DEPTID <> 1001;

-- SELECT HR AND SALES EMPLOYEES
SELECT * FROM EMPLOYEE
WHERE DEPTID IN (1002,1003);

-- SALARY GREATER THAN 35000
SELECT * FROM EMPLOYEE
WHERE SALARY > 35000;

-- SALARY LESS OR EQUAL 35000
SELECT * FROM EMPLOYEE
WHERE SALARY <= 35000;

-- TOTAL EMPLOYEE COUNT
SELECT COUNT(*) AS "TOTAL EMPLOYEES" FROM EMPLOYEE;

-- TOTAL SALARY
SELECT SUM(SALARY) AS "TOTAL SPEND" FROM EMPLOYEE;

-- IT EMPLOYEE COUNT
SELECT COUNT(*) AS "IT EMP COUNT"
FROM EMPLOYEE
WHERE DEPTID = 1001;

-- NON IT EMPLOYEE COUNT
SELECT COUNT(*) AS "NON IT EMP COUNT"
FROM EMPLOYEE
WHERE DEPTID <> 1001;