USE IT_COMPANY1;
-- FIND  THE IT DEPT EMPLOYEE COUNT
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPT;

SELECT DEPTID, COUNT(*)AS "IT EMPLOYEE"FROM EMPLOYEE
WHERE DEPTID=1002;

-- FIND SALES DEPT EMPLOYEE COUNT
SELECT  DEPTID,COUNT(*) AS "SALES DEPT "FROM DEPT
WHERE DEPTID=1003;
-- FIND HR DEPT EMPLOYEE COUNT
SELECT COUNT(*) AS  "HR DEPT" FROM EMPLOYEE
WHERE DEPTID=1002 OR DEPTID=1001;
SELECT NAME,DEPTID,COUNT(*) AS COUNT FROM EMPLOYEE
GROUP BY DEPTID;
SELECT DEPTID,COUNT(*) AS COUNT ,SUM(SALARY)FROM EMPLOYEE
GROUP BY DEPTID;

SELECT * FROM EMPLOYEE;
-- FIND MAXIMUM SALARY IN EACH DEPT
SELECT deptid, MAX(salary) AS max_salary
FROM employee
GROUP BY deptid;
-- FIND MINIMUM SALARY IN EACH DEPT
SELECT deptid, MIN(salary) AS min_salary
FROM employee
GROUP BY deptid;
-- FIND HOW MUCH AVERAGE SALARY COMPANY SPENDS ON EACH DEPY
SELECT deptid, AVG(salary) AS avg_salary
FROM employee
GROUP BY deptid;
-- RETURN 1001 AND 1002 DEPT'S MINIMUM SALARY
SELECT deptid, MIN(salary) AS min_salary
FROM employee
WHERE deptid IN (1001,1002)
GROUP BY deptid;
-- RETURN ALL DEPT'S TOTAL_EMPLOYEE
SELECT deptid, COUNT(*) AS total_employee
FROM employee
GROUP BY deptid;
-- FIND EACH DEPT TOTAL SALARY
SELECT deptid, SUM(salary) AS total_salary
FROM employee
GROUP BY deptid;