-- select database
USE IT_COMPANY1;

-- CHECK TABLES
SHOW TABLES;

-- CHECK DEPT TABLE DATA AND EMPLOYEE DATA
SELECT * FROM DEPT;
 SELECT * FROM EMPLOYEE;
 INSERT  INTO  EMPLOYEE(NAME,DEPTID,SALARY) VALUES('RAJ',1006,345555);
 
 -- INNER JOIN 
 -- SELECT EMPID,NAME AND DEPTNAME FROM DEPT AND EMPLOYEE TABLES
 SELECT  EMPID,NAME,DEPTNAME FROM DEPT
 INNER JOIN EMPLOYEE 
 ON DEPT.DEPTID=EMPLOYEE.DEPTID;
 
 -- SELECT ONLY IT DEPT RECORDS
  SELECT  EMPID,NAME,DEPTNAME FROM DEPT
 INNER JOIN EMPLOYEE 
 ON DEPT.DEPTID=EMPLOYEE.DEPTID
 WHERE DEPTNAME='IT';
 -- COUNT EACH DEPT MEMBERS
SELECT DEPTNAME, COUNT(*)FROM DEPT
 INNER JOIN EMPLOYEE 
 ON DEPT.DEPTID=EMPLOYEE.DEPTID
 GROUP BY DEPTNAME;
 -- LEFT JOIN 
  SELECT  EMPID,NAME,DEPTNAME FROM DEPT
 LEFT JOIN EMPLOYEE 
 ON DEPT.DEPTID=EMPLOYEE.DEPTID;
 
 -- CREATE NEW TABLE DEPT1
 CREATE TABLE DEPT1(ID INT,NAME VARCHAR(20),LOCATION VARCHAR(20) DEFAULT'INDIA');
 -- INSERT DATA INTO DEPT1 TABLE
 INSERT INTO DEPT1(ID,NAME,LOCATION)VALUES(1001,"IT","USA"),(1002,"SALES","UAE");
 
  INSERT INTO DEPT1(ID,NAME)VALUES(1004,"HR"),(1005,"MARKTING");
  
  -- CHECKING TABELE DATA
  SELECT * FROM DEPT1;
  -- left  join
SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 LEFT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID;
 
 -- RIGHT JOIN
 SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 RIGHT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID;
 -- FULL JOIN NOT WORK IN SQL SO WE USE SET OPERATIONS LIKE(UNION,UNION ALL,INSERSECTION ,EXCEPT)
  (SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 RIGHT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID)
 UNION
 (SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 LEFT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID);
 
 (SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 RIGHT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID)
 UNION ALL
 (SELECT ID, DEPT1.NAME,EMPID,EMPLOYEE.NAME FROM DEPT1
 LEFT JOIN EMPLOYEE 
 ON DEPT1.ID=EMPLOYEE.DEPTID);